539cc1
/**
* Global predefined variable for .install and .module
23f
define('DRUPAL_EOL_REDIRECTOR_404_PATH', 'eol_redirector/404');

2389
* hook_menu for page callback eol_redirector()
*/
f037e330 7341f6e138772d719a6d4 4

  $site_404 = variable_get('site_404');
  $items[$site_404] = array(
  074d60f            c5 8df57de2 b7074d60f
  'page callback' => 'eol_redirector',
  'access arguments' => array('access content'),
  a41
  return $items;
}
75095d15 7d68ce947a882dd5 b1
  //issue: drupal_goto gets stuck in an redirect loop
  //drupal_goto("https://www.elance.com/php/search/main/404.php");
  1c1294b2197182462 cb86abc15247
501c1294b21971824620cb86abc15247
501c
  exit;
}
4
/**
* Prevents updates to 404 path in admin, verifies and updates if necessary on all content(cached and uncached pages)
ab6
function eol_redirector_boot(){
  //variable_del('site_404');
  a02f919a2ca2c130e5bc33e4aa 883
d1a02f919a2ca2c130e5bc33e4aa5
  $menu_404_path = 'eol_redirector/404';
  $site_404 = variable_get('site_404');
  c10  585a853adf04fbb36 67  17d
95c10 25 5a853adf04fbb3 2 7d
    variable_del('site_404');
    variable_set('site_404', $menu_404_path);
    b2074823c c a49b77538632a810
38bbb2074
  }  
}
4d0a
* (uncached pages)
*/
3c333f46 633581ac55fefff6b56a468

}